### ISSUE TITLE
Receive signal SIGABRT when invoke log function in easylogging++ at thread safe mode.

### ISSUE THREAD

**Issue by gazall** [gazall/ethan#1]
build easylogging++ with macro ELPP_THREAD_SAFE.

bt:
Program received signal SIGABRT, Aborted.
0x00007ffff7009207 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7009207 in raise () from /lib64/libc.so.6
#1  0x00007ffff700a8f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff79187d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff7916746 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff7916773 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff7916993 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff796bbc7 in std::__throw_ios_failure(char const*) () from /lib64/libstdc++.so.6
#7  0x00007ffff7934caa in std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate) () from /lib64/libstdc++.so.6
#8  0x00007ffff794e719 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /lib64/libstdc++.so.6
#9  0x00007ffff794ebf7 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) () from /lib64/libstdc++.so.6
#10 0x000000000047ad78 in el::base::MessageBuilder::operator<< (this=0x7fffffffe118, msg=0x4ad578 "first info")
    at /home/ethan/Code/ethan/./base/easylogging++.h:2888
#11 0x000000000047af91 in el::base::Writer::operator<< <char [11]> (this=0x7fffffffe0d0, log=...)
---Type <return> to continue, or q <return> to quit---
    at /home/ethan/Code/ethan/./base/easylogging++.h:3210
#12 0x000000000047ab2c in main () at /home/ethan/Code/ethan/test/log_test.cc:33

**Comment by gazall** [comment]
Build any code include easylogging++ with macro ELPP_THREAD_SAFE, not only easylogging++ itself.

Detail: https://github.com/amrayn/easyloggingpp/issues/193
